( CONVOY BOMB      83.05.07)                                    
: B 0 N ! CLS VISA-P 0 AB ! 1 VB !  VATTEN                      
BEGIN FLYG FLYT ?BOMB @ IF FALL ELSE BOMBINIT THEN -1 ?S +!     
FLYG ?S @ 0= IF SUDDA THEN AB @ 5 = UNTIL ;                     
: IT CLS CR CR 6 SPACES ." C O N V O Y   B O M B" CR CR         
." DITT UPPDRAG AR ATT SANKA ALLA" CR ." FARTYGEN I EN KONVOJ. K
ONVOJEN" CR ." BESTAR AV 8 HANDELSFARTYG." CR ." DU FAR POANG F0
R VARJE SANKT" CR ." SKEPP OCH POANGAVDRAG F0R VARJE" CR        
." 0VERFLYGNING." CR ." F0R ATT FALLA EN BOMB, TRYCK NER"       
." <B> TILLS DU SER BOMBEN FALLA." CR ." DU KAN INTE FALLA NASTA
 BOMB" CR ." F0RREN DEN F0RRA HAR LANDAT." CR ." DU KAN EJ REGLE
RA H0JDEN EFTER-" CR ." SOM DU EJ AR PILOT UTAN BOMB-" CR       
." FALLARE." CR ." F0R ATT B0RJA, SKRIV <N/L>." ;               
: CONVOY-BOMB BEGIN IT VISA B HOME CR CR CR CR ." VILL DU SPELA 
EN GANG TILL?(J/N)" 0 BEGIN DROP KEY DUP DUP 78 = SWAP 74 = OR U
NTIL 78 = UNTIL CLS ." ADJ0. HOPPAS NI HADE TREVLIGT." CR ; ;S  